# project information for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}Bukkit

# meta information for plugin managers
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

softdepend:
  - ProtocolLib
  - PacketListenerAPI

commands:
  packet-filter:
    description: 'Filters the packets that should be printed to the console'
    usage: '/<command> <phase/player/id> <add/remove>'

  packet-listener:
    description: 'Starts or stops the listener'
    usage: '/<command> <start/stop>'
